-- Location Intelligence LATAM: tables, spatial metadata and spatial indexes
-- Target: Oracle Autonomous Database (26ai) with Oracle Spatial

create table laouc_locations (
  location_id        number generated by default as identity primary key,
  location_code      varchar2(30)  not null,
  location_name      varchar2(120) not null,
  category           varchar2(40)  not null,  -- CENTRO_DISTRIBUCION, CENTRO_SERVICIO, SUCURSAL, CLIENTE
  country_name       varchar2(60)  not null,
  city_name          varchar2(80)  not null,
  street_address     varchar2(200) not null,
  latitude           number        not null,
  longitude          number        not null,
  operational_status varchar2(20)  not null,
  geocode_status     varchar2(30)  not null,
  geom               sdo_geometry  not null,
  -- Written back by the Spatial Studio "Calculate driving route" analysis
  drive_time         number,       -- minutes
  drive_distance     number,       -- km
  route_geom         sdo_geometry,
  drive_time1        number,
  drive_distance1    number,
  constraint laouc_locations_status_ck check (operational_status in ('ACTIVA','PENDIENTE'))
);

create table laouc_regions (
  region_id    number generated by default as identity primary key,
  region_code  varchar2(30)  not null,
  region_name  varchar2(120) not null,
  country_name varchar2(60)  not null,
  city_name    varchar2(80)  not null,
  geom         sdo_geometry  not null
);

create table laouc_geocode_requests (
  request_id     number generated by default as identity primary key,
  location_name  varchar2(120) not null,
  country_name   varchar2(60)  not null,
  city_name      varchar2(80)  not null,
  street_address varchar2(200) not null,
  latitude       number,
  longitude      number,
  gc_geometry    sdo_geometry,
  geocode_status varchar2(30)  not null,
  studio_job_id  varchar2(100),
  created_at     timestamp default systimestamp not null,
  processed_at   timestamp,
  constraint laouc_geocode_status_ck
    check (geocode_status in ('PENDIENTE','ENVIADA_A_STUDIO','GEOCODIFICADA','ERROR'))
);

-- Spatial metadata (WGS84, lon/lat)
insert into user_sdo_geom_metadata (table_name, column_name, diminfo, srid)
select t, c,
       sdo_dim_array(sdo_dim_element('X', -180, 180, 0.05),
                     sdo_dim_element('Y',  -90,  90, 0.05)),
       4326
from (select 'LAOUC_LOCATIONS' t, 'GEOM' c from dual
      union all select 'LAOUC_LOCATIONS', 'ROUTE_GEOM' from dual
      union all select 'LAOUC_REGIONS', 'GEOM' from dual
      union all select 'LAOUC_GEOCODE_REQUESTS', 'GC_GEOMETRY' from dual);
commit;

-- Spatial indexes
create index sidx_laouc_locations_geom on laouc_locations (geom) indextype is mdsys.spatial_index_v2;
create index sidx_laouc_regions_geom   on laouc_regions (geom)   indextype is mdsys.spatial_index_v2;
create index sidx_laouc_geocode_geom   on laouc_geocode_requests (gc_geometry) indextype is mdsys.spatial_index_v2;
